const profileFieldLabels: Record<string, string> = {
  company_name: '企业名称',
  credit_code: '统一社会信用代码',
  city: '所在城市',
  district: '所在区',
  registered_year: '成立年份',
  listed_status: '上市状态',
  employee_count: '员工人数',
  employee_range: '员工人数区间',
  industry: '所属行业',
  main_business: '主营业务',
  main_products: '主要产品',
  customer_type: '客户类型',
  business_model: '商业模式',
  main_revenue_source: '主要收入来源',
  revenue_last_year: '上一年度营收',
  revenue_range: '营收区间',
  profit_last_year: '上一年度利润',
  profit_range: '利润区间',
  tax_paid_last_year: '上一年度纳税额',
  tax_paid_range: '纳税额区间',
  rd_expense_last_year: '上一年度研发费用',
  rd_expense_range: '研发费用区间',
  rd_expense_ratio: '研发投入占比',
  rd_employee_count: '研发人员数量',
  rd_employee_range: '研发人员区间',
  is_high_tech_enterprise: '高新技术企业资质',
  is_tech_sme: '科技型中小企业资质',
  has_specialized_new_sme: '专精特新资质',
  patent_count: '专利数量',
  software_copyright_count: '软件著作权数量',
  tax_credit_level: '税务信用等级',
  has_major_violation: '重大违法违规记录',
  social_security_normal: '社保缴纳状态',
  apply_project_name: '申报项目名称',
  project_direction: '项目方向',
  project_stage: '项目阶段',
  project_budget: '项目预算',
  project_budget_range: '项目预算区间',
  registered_capital: '注册资本',
  business_address: '经营地址',
  legal_representative: '法定代表人',
  establishment_date: '成立日期',
  registration_status: '登记状态',
  is_headquarters: '总部企业情况',
  is_above_scale_enterprise: '规上企业情况',
  digital_transformation_status: '数字化转型情况',
  award_titles: '奖项荣誉',
  known_projects: '在研或建设项目',
  production_projects: '已投产或落地项目',
  company_identity_verification: '企业主体核验信息'
};

export function profileFieldLabel(fieldKey: string): string {
  return profileFieldLabels[fieldKey] ?? `其他企业信息：${fieldKey}`;
}
